config/routes.rb
Rails.application.routes.draw do
  resources :time_tables
  resources :tags
  resources :messages
  resources :attatchments
  resources :after_signup
  resources :bookmarks, only: [:index, :create]
  devise_for :users, :controllers => { registrations: 'registrations' }
  match '/users/:id', :to=> 'users#show' , :as=> :user, :via=> :get 
  match '/users', :to=> 'users#index', :as=> :users, :via=> :get 
  root to: "home#index"
  get '/about' => 'home#about'
  get 'dashboard' => 'home#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  resources :conversations do
    resources :messages do
      member do
        post 'add_remove_star'
        post 'add_remove_imp'
      end
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
  has_many :bookmarks
  has_many :users, through: :bookmarks
  has_many :attatchments, dependent: :destroy
  accepts_nested_attributes_for :attatchments, reject_if: :all_blank
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:update, :destroy]
  before_action :authenticate_user!

  def create
    @message = Message.new
    @message.body = params[:message][:body]
    @message.conversation_id = params[:message][:conversation_id]
    @message.user= current_user
    authorize @message
    respond_to do |format|
      if @message.save
        if params[:message][:attatchments_attributes]
          params[:message][:attatchments_attributes].each do |attatchment|
            Attatchment.create!(file: attatchment[:file], message: @message) unless attatchment[:file].blank?
          end
        end

        format.json {}
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
      authorize @message
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit!
      #params.require(:message).permit(:body, :conversation_id, attatchments_attributes: [:file])
    end
end

app/views/messages/_form.html.erb
<%= simple_form_for(@message, {:remote =>true}) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
    </div>
  <% end %>
  <%= f.simple_fields_for :attatchments do |attatchment_form| %>
    <span id="fake_file_btn">+</span>
    <%= attatchment_form.input :file, :label=>false, input_html: {multiple: true,  :name=>'message[attatchments_attributes][][file]'} %>
  <% end %>
  <div class="field">
    <%= f.input :body, {:label=>false, :as=>'text', :input_html=>{:placeholder=>'Type your messages', :class=>'submit_on_enter'}} %>
    <div id="progress">
        <div class="bar" style="width: 0%;"></div>
    </div>
  </div>
  <%= f.input :conversation_id, {:as=>'hidden', :input_html=>{:value=>@conversation.id}} %>
<% end %>

app/views/messages/_message.html.erb
<div class="row1">
  <div class="col-md-12 chhat">
    <div class="user-img"><img src="<%= message.user.avatar.url(:thumb) %>" /></div>
    <div class="chat-section">
      <p class="user-name"><%= message.user.name %></p>
      <%= simple_form_for(Bookmark.new, {:remote =>true}) do |f| %>
          <%= f.input :message_id, {:label=>false, :as=>'hidden', :input_html=>{:value=>message.id}} %>
          <%= f.button :submit, :id=>"bookmark_#{message.id}", value: '', class: (message.users.include?(current_user)) ? 'star' : 'empty_star' %>
      <% end %>
      <p><%= time_ago_in_words(message.created_at) %> ago</p>
      <div class="message-user"><%= raw simple_format message.body %></div>
      <% message.attatchments.each do |attatchment| %>
        <div class="col-md-2">
          <% if ['jpg', 'jpeg', 'png', 'gif'].include?(attatchment.file.file.extension) %>
            <%= image_tag attatchment.file.url, class: 'img-thumbnail' %>
          <% else %>
            <%= link_to  File.basename(attatchment.file.path), attatchment.file.url, class: 'file_download_link' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/create.js.erb
socket.emit('message', { conversation_id: <%= @message.conversation.id %>, conversation_name: '<%= @message.conversation.name %>', conversation_kind: '<%= @message.conversation.kind %>', sender_user_id: <%= current_user.id %>, sender_user_name: '<%= current_user.name %>', message: '<%= escape_javascript(render(@message)) %>', link: '<%= conversation_url(@message.conversation) %>', body: '<%= @message.body %>'});

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Conversation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.body %></td>
        <td><%= message.user %></td>
        <td><%= message.conversation %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Messgae</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user %>
</p>

<p>
  <strong>Conversation:</strong>
  <%= @message.conversation %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>