config/routes.rb
Rails.application.routes.draw do
  resources :time_tables
  resources :tags
  resources :messages
  resources :attatchments
  resources :after_signup
  resources :bookmarks, only: [:index, :create]
  devise_for :users, :controllers => { registrations: 'registrations' }
  match '/users/:id', :to=> 'users#show' , :as=> :user, :via=> :get 
  match '/users', :to=> 'users#index', :as=> :users, :via=> :get 
  root to: "home#index"
  get '/about' => 'home#about'
  get 'dashboard' => 'home#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  resources :conversations do
    resources :messages do
      member do
        post 'add_remove_star'
        post 'add_remove_imp'
      end
    end
  end

end

app/controllers/time_tables_controller.rb
class TimeTablesController < ApplicationController
  before_action :set_time_table, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /time_tables
  # GET /time_tables.json
  def index
    authorize TimeTable
    if(params[:user_id])
      @time_tables = User.find(params[:user_id]).time_tables.where({:privacy=>'open'})
    else
      @time_tables = current_user.time_tables
    end
  end

  # GET /time_tables/1
  # GET /time_tables/1.json
  def show
  end

  # GET /time_tables/new
  def new
    @time_table = TimeTable.new
    authorize @time_table
  end

  # GET /time_tables/1/edit
  def edit
  end

  # POST /time_tables
  # POST /time_tables.json
  def create
    @time_table = TimeTable.new(time_table_params)
    @time_table.user = current_user
    authorize @time_table
    respond_to do |format|
      if @time_table.save
        format.html { redirect_to @time_table, notice: 'Time table was successfully created.' }
        format.json { render :show, status: :created, location: @time_table }
      else
        format.html { render :new }
        format.json { render json: @time_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_tables/1
  # PATCH/PUT /time_tables/1.json
  def update
    respond_to do |format|
      if @time_table.update(time_table_params)
        format.html { redirect_to @time_table, notice: 'Time table was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_table }
      else
        format.html { render :edit }
        format.json { render json: @time_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_tables/1
  # DELETE /time_tables/1.json
  def destroy
    @time_table.destroy
    respond_to do |format|
      format.html { redirect_to time_tables_url, notice: 'Time table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_table
      @time_table = TimeTable.find(params[:id])
      authorize @time_table
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_table_params
      params.require(:time_table).permit(:title, :description, :start, :end, :privacy, :user_id)
    end
end

app/helpers/time_tables_helper.rb
module TimeTablesHelper
end

app/views/time_tables/_form.html.erb
<%= simple_form_for(@time_table) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :start %>
    <%= f.input :end %>
    <%= f.input :privacy, as: :select, collection: TimeTable.privacies.keys.to_a, :include_blank => false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/time_tables/edit.html.erb
<h1>Editing Time Table</h1>

<%= render 'form', time_table: @time_table %>

<%= link_to 'Show', @time_table %> |
<%= link_to 'Back', time_tables_path %>

app/views/time_tables/index.html.erb
<div class="col-md-12">
  <%= link_to 'Add Event', new_time_table_path(@time_table), class: 'add btn btn-primary' %>
</div>
<div id="event_calendar_full"></div>
<div id="event_modal" class="modal hide fade" tabindex="-1" data-width="400" data-height="350" style="height:300px;">
  <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn">Close</button>
  </div>
</div>

app/views/time_tables/new.html.erb
<h1>New Time Table</h1>

<%= render 'form', time_table: @time_table %>

<%= link_to 'Back', time_tables_path %>

app/views/time_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @time_table.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @time_table.description %>
</p>

<p>
  <strong>Start:</strong>
  <%= @time_table.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @time_table.end %>
</p>

<p>
  <strong>Privacy:</strong>
  <%= @time_table.privacy %>
</p>

<p>
  <strong>User:</strong>
  <%= @time_table.user.name %>
</p>

<%= link_to 'Edit', edit_time_table_path(@time_table), class: "btn btn-inverse" %> |
<%#= link_to 'Back', time_tables_path %>