config/routes.rb
Rails.application.routes.draw do
  resources :time_tables
  resources :tags
  resources :messages
  resources :attatchments
  resources :after_signup
  resources :bookmarks, only: [:index, :create]
  devise_for :users, :controllers => { registrations: 'registrations' }
  match '/users/:id', :to=> 'users#show' , :as=> :user, :via=> :get 
  match '/users', :to=> 'users#index', :as=> :users, :via=> :get 
  root to: "home#index"
  get '/about' => 'home#about'
  get 'dashboard' => 'home#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  resources :conversations do
    resources :messages do
      member do
        post 'add_remove_star'
        post 'add_remove_imp'
      end
    end
  end

end

app/views/layouts/_chat.html.erb
<script src="<%= ENV['CHAT_SERVER'] %>/socket.io/socket.io.js"></script>
<script>
  var socket = io.connect('<%= ENV['CHAT_SERVER'] %>');
  window.name = "crumchat"
</script>

<% if user_signed_in? %>
  <script >
    <% if controller_name == 'conversations' and action_name == 'show' %>
      
      console.log('#conversation_<%= @conversation.id %>')
      $(document).ready(function(){
        d = $('#conversation_<%= @conversation.id %>')
        d.scrollTop(d.prop("scrollHeight"));
      });
      
    <% end %>
    socket.on('connect', function() {
       // Connected, let's sign-up for to receive messages for this room
       <% current_user.conversations.each do |conversation| %>
        socket.emit('room', <%= conversation.id %>);
       <% end %>
    });
    socket.on('message', function(msg){
      appended = false;
      <% if controller_name == 'conversations' and action_name == 'show' %>
        if(<%= @conversation.id %> == msg.conversation_id){
          $(document).ready(function(){
            d.append(msg.message).scrollTop(d.prop("scrollHeight"));
            appended = true;
          });
        }
      <% end %>
      if((msg.sender_user_id != <%= current_user.id %>) && !appended){
        if(msg.conversation_kind == 'channel'){
          title = "in " + msg.conversation_name
        }else{
          title = ''
        }
        
        notifyMe(title, msg)
      }
    });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrumNewchat</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= render 'layouts/chat' %>
  </head>

  <body>
  <div class='row'>
    <div class="ui header left floated white-text">
      <div class='col-md-4'>
        <div class='logo'><%= link_to 'Crum', root_path %></div>
      </div>
      <div class="col-md-8 pull-right">
        <ul class='nav navbar-nav'>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "My Time table", time_tables_path %></li>
          <li><%= link_to "Conversations", conversations_path %></li>
          <li><%= link_to "Bookmarks", bookmarks_path %></li>
          <li><%= link_to "Tags", tags_path %></li>
        </ul>
        <span><%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'logout' %></span>
      </div>
    </div>
    <%= yield %>
  </div>
  </body>
</html>